spring:
  application:
    name: chat-manager
  profiles:
    active: dev
  config:
    import: configserver:http://92.63.103.228:8888

com:
  chat-manager:
    notification:
      url: http://localhost:8080/notification/